Added ability to restore position with the _exit_point
jlas1/Klicky-Probe pull request #30
Opened 2021-12-16 18:00 UTC by Frix-x

Hey, here is mainly an aesthetic PR to simplify some macros.

First I added the option to restore the nozzle position using the _exit_point macro at a set speed.
Secondly, this also enable us to simplify the PROBE_ACCURACY and PROBE_CALIBRATE custom overrides by removing/replacing the multiples SAVE_GCODE_STATE and RESTORE_GCODE_STATE calls.

2021-12-16 22:11 UTC, jlas1 requested changes
Please check the comments, the simplification goes against the objective of having the code always reverting to the state that it was before being called

2021-12-16 22:11 UTC, jlas1 commented on Klipper_macro/klicky-probe.cfg
> +        G90
By forcing a G90 without doing a save first, you lose the previous state, that is not desired.

2021-12-16 22:11 UTC, jlas1 commented on Klipper_macro/klicky-probe.cfg
> +        G90
By forcing a G90 without doing a save first, you lose the previous state, that is not desired.

2021-12-16 22:11 UTC, jlas1 commented on Klipper_macro/klicky-probe.cfg
> +    RESTORE_GCODE_STATE NAME={function} MOVE={move} MOVE_SPEED={speed}
nice idea

2021-12-17 18:02 UTC, Frix-x commented on Klipper_macro/klicky-probe.cfg
> +        G90
Oh yes, you're right, I did not think about it !

So even if the main modification is cool (add move/speed control to _exit_point), the simplification of PROBE_CALIBRATE and PROBE_ACCURACY is not really possible due to that G90. I'll try to see how to do it the best without this regression.

2021-12-17 18:03 UTC, Frix-x commented on Klipper_macro/klicky-probe.cfg
> +    RESTORE_GCODE_STATE NAME={function} MOVE={move} MOVE_SPEED={speed}
This is the main subject of the PR to remove the need of all the SAVE/RESTORE_GCODE_STATE and use only the _entry_point and _exit_point :)

2021-12-18 11:53 UTC, jlas1 commented
Can you update the files on the PR? You can update them on your branch that it will be updated here.

2022-01-09 17:15 UTC, jlas1 commented
I'm gonna close this PR as the macros have changed a lot.
I have included the speed function on the _exit_point macro, thanks for that.

2022-01-09 17:15 UTC, closed without merging

2022-01-10 10:16 UTC, Frix-x commented
Sorry I was on vacation until today without proper internet access.
No problem, speed in the _exit_point macro was the main point of the PR :)